const pipelineSteps = [
  {
    id: 'intent', label: 'Human intent', category: 'The starting point', tone: 'neutral',
    title: 'Define done before the work begins.',
    description: 'Start with a feature, a bug report, or a question to investigate. People define the desired outcome, the boundaries, and what evidence would make the work complete.',
    points: ['Feature: define the behavior and acceptance criteria.', 'Bug: describe expected vs. actual behavior and how to reproduce it.', 'Investigation: name the question, scope, and evidence needed.'],
    example: 'Customers report duplicate orders after a timeout. First investigate whether retries are the cause. Return the evidence, remaining unknowns, and a recommended next step; a fix can follow.',
    takeaway: 'Done can be a verified change—or a well-supported answer.',
    view: [0, -110, 500, 360],
  },
  {
    id: 'orchestration', label: 'Orchestration', category: 'The delivery path', tone: 'neutral',
    title: 'Match the model and budget to the work.',
    description: 'The orchestrator identifies the task type, complexity, and risk, then chooses the agent, model, and relevant skills. A quick investigation and a large migration need different execution plans.',
    points: ['Choose a small or large model to suit the task and reasoning needed.', 'Use a bounded task for short work or a goal for sustained work.', 'Allocate a token budget, time limit, checkpoints, and stop conditions.'],
    exampleLabel: 'IN PRACTICE / A LARGE MIGRATION',
    example: 'Create a goal with a clear end state. Assign a larger model to plan the migration, allocate a share of the team’s token budget, and reserve tokens for verification. Review progress at checkpoints before committing more budget.',
    takeaway: 'Make the outcome, model choice, and spending limits explicit.',
    view: [0, -30, 560, 320],
  },
  {
    id: 'context', label: 'Organizational context', category: 'A compounding asset', tone: 'teal',
    title: 'Give the work your organization’s memory.',
    description: 'An agent can write good code and still repeat an old mistake if it cannot find why a decision was made. Give it easy access to the rationale, constraints, and history behind the system.',
    points: ['Commit specs and decision records in the same repo where practical.', 'For external records, keep clear links the agent can follow and access.', 'Record the tradeoffs, rejected alternatives, and incidents behind decisions.'],
    example: 'A repo-linked decision record explains why deduplication lives in the order service: client-only checks once allowed duplicate orders after timeouts. The agent reads that history before proposing a simpler retry flow.',
    takeaway: 'Make the why as accessible as the code.',
    view: [0, -45, 980, 390],
  },
  {
    id: 'execution', label: 'Execution sandbox', category: 'From local to cloud', tone: 'muted',
    title: 'Give agents the whole working environment.',
    description: 'Today, agents mostly run on our local machines. Build toward reproducible cloud workspaces where an agent can set up what it needs, run the product, inspect failures, and iterate on a change.',
    points: ['Provision isolated workspaces, PR previews, and scoped test databases.', 'Use our standard setup to boot services, a browser, and mobile runtimes.', 'Support computer use, performance checks, and screenshots or video.'],
    exampleLabel: 'TARGET WORKFLOW / BOOT, TEST, ITERATE',
    example: 'The agent starts the services, seeds test data, and exercises the PR environment. For iOS work, it boots a simulator on a macOS runner. It captures behavior, fixes failures, and returns the change with evidence for independent review.',
    takeaway: 'The agent should be able to reproduce the environment and the result.',
    view: [0, -15, 980, 455],
  },
  {
    id: 'tools', label: 'Tool layer', category: 'A compounding asset', tone: 'teal',
    title: 'Tools need access, guidance, and upkeep.',
    description: 'Connect databases, logs, CI checks, browsers, and MCP integrations for services such as Sentry and Datadog. An agent investigating a bug or incident should be able to retrieve the evidence it needs.',
    points: ['Supply scoped credentials automatically for authorized tasks.', 'Maintain skills for choosing tools, querying data, and interpreting results.', 'Monitor availability, authentication, and tool errors; route failures to an owner.'],
    exampleLabel: 'IN PRACTICE / INVESTIGATING AN INCIDENT',
    example: 'Trace a duplicate-order report from Sentry to Datadog logs, query the affected records, and inspect relevant CI results. If a connector fails, flag the missing evidence and route the issue for repair instead of treating it as “nothing found.”',
    takeaway: 'A connected tool must also be usable, reliable, and maintained.',
    view: [0, -15, 980, 455],
  },
  {
    id: 'verification', label: 'Independent verification', category: 'The constraint', tone: 'amber',
    title: 'Verify often. Earn confidence independently.',
    description: 'As agents produce more changes, verification needs to run more often: during implementation, before the PR, and in CI. Check the original requirements against actual behavior.',
    points: ['Keep linting and tests fast and repeatable; have agents fix bottlenecks and flakes.', 'Write meaningful end-to-end tests; attach Playwright videos and results to the PR.', 'Use a separate review agent with fresh context, the requirements, and the diff.'],
    exampleLabel: 'IN PRACTICE / TEST, RECORD, REVIEW',
    example: 'The test asserts that one order exists after a timeout and retry. Attach its Playwright recording and results to the PR; a separate agent checks the behavior and challenges the assumptions with fresh context.',
    takeaway: 'Fast, trustworthy checks make frequent verification practical.',
    view: [0, 0, 980, 565],
  },
  {
    id: 'memory', label: 'Memory & skills', category: 'A compounding asset', tone: 'teal',
    title: 'Keep the lesson after the task is over.',
    description: 'A repeated PR comment is a signal that knowledge is missing upstream. Distill the lesson into the docs, skills, and checks used to plan and implement the next feature.',
    points: ['Update the tech-spec and feature-implementation skills.', 'Put domain-specific lessons in the relevant domain skill.', 'Add review guidance and an executable check when possible.'],
    example: 'Repeated comments about retry safety become a spec question, an implementation pattern, a review check, and a regression test.',
    takeaway: 'Build it right earlier; keep the later checks too.',
    view: [0, 0, 980, 565],
  },
  {
    id: 'gate', label: 'Confidence gate', category: 'The decision point', tone: 'neutral',
    title: 'Match the sign-off to the risk.',
    description: 'An agent assesses risk using the change, verification evidence, and past incidents. It can publish a readiness sign-off that helps human reviewers understand what is checked and what still needs judgment.',
    points: ['Assess impact, affected systems, and relevant incident history.', 'Back “ready for review” with independent checks and remaining uncertainties.', 'Route reviewers by ownership, expertise, and availability; follow sign-off policy.'],
    exampleLabel: 'IN PRACTICE / READINESS AND REVIEW ROUTING',
    example: 'The retry fix passes independent checks. The agent posts a readiness sign-off with test evidence and a relevant past incident, then recommends the order-service owner as reviewer because the change affects order creation.',
    takeaway: 'Make readiness visible and bring in the right people.',
    view: [0, 0, 980, 685],
  },
  {
    id: 'judgment', label: 'Human judgment', category: 'The accountable decision', tone: 'neutral',
    title: 'Use human judgment to validate the intent.',
    description: 'Strong planning and verification should reduce routine code corrections at PR review. Focus human attention on whether we built the right thing, and bring people in early to validate the experience and tradeoffs.',
    points: ['Show early previews to designers, project managers, and engineering leads.', 'Focus final sign-off on intent, actual behavior, and remaining risk.', 'Feed recurring code issues into planning, implementation, and review skills.'],
    exampleLabel: 'IN PRACTICE / ALIGN EARLY, IMPROVE CONTINUOUSLY',
    example: 'An early preview reveals a confusing retry flow. Clarify the spec before implementation proceeds. If human review keeps catching the same retry mistakes, update the relevant skills and checks so the next change starts with that lesson.',
    takeaway: 'Human review improves this change and how the next one is built.',
    view: [0, 0, 980, 685],
  },
  {
    id: 'release', label: 'Release', category: 'The delivery path', tone: 'neutral',
    title: 'Ship the change. Observe what happens.',
    description: 'Low-risk changes may release directly when policy allows. Others arrive through human sign-off. Both paths lead to production behavior we can observe.',
    points: ['Release with an appropriate rollout and recovery plan.', 'Watch the behavior the change was intended to improve.', 'Capture regressions, incidents, and real usage.'],
    example: 'Roll out the fix and monitor duplicate-order reports, retry outcomes, and error rates. Compare actual behavior with the acceptance criteria.',
    takeaway: 'Shipping creates the next source of evidence.',
    view: [0, 0, 980, 748],
  },
  {
    id: 'feedback', label: 'The feedback loop', category: 'The compounding loop', tone: 'teal',
    title: 'Send every lesson back upstream.',
    description: 'PR feedback, local review, CI, production signals, and incidents all teach us something. Each lesson should improve the earliest part of the process that could have prevented the problem.',
    points: ['Identify where the issue could have been prevented or caught.', 'Update the relevant docs, planning skills, and implementation skills.', 'Keep a regression check and verify that the lesson actually sticks.'],
    example: 'An incident exposes a missed retry case. Update the tech-spec prompt and service skill, then add local-review guidance and a regression test.',
    takeaway: 'Anything learned later should make earlier work better.',
    view: [0, 0, 980, 748],
  },
  {
    id: 'complete', label: 'The complete picture', category: 'The system, together', tone: 'teal',
    title: 'Build a system that earns trust.',
    description: 'Generation is one part of the pipeline. Independent verification establishes confidence, while context, tools, and memory make the whole system more capable over time.',
    points: ['The delivery path moves intent toward a release.', 'The amber stage makes confidence the focus.', 'The teal assets and feedback loop compound.'],
    example: 'One fixed retry bug leaves behind more than code: a clearer spec, a stronger test suite, a reusable skill, and better context for the next change.',
    takeaway: 'The asset is the system around the model.',
    view: [0, 0, 980, 748],
  },
];

const domainSkills = {
  id: 'domain-skills', panel: 'skills', label: 'Bring in the right skills', category: 'Before implementation', tone: 'teal',
  title: 'Make domain expertise available to everyone.',
  description: 'Domain experts write and maintain the skills. The orchestrator brings in the right guidance before work begins, so every developer and agent benefits from the same expertise.',
  points: ['Give each skill an expert owner who authors and validates it.', 'Keep incorporating best practices, research, and real feedback.', 'Check outcomes, refine the guidance, and repeat as the system evolves.'],
  exampleLabel: 'EXAMPLE / A GRID FEATURE',
  example: 'The grid expert captures editing rules and performance lessons in the Handsontable skill. Anyone building a bulk-edit feature gets that guidance. Review feedback and production results help the expert improve it for the next person.',
  takeaway: 'Everyone starts with the team’s best current knowledge.',
  diagramStage: 1, view: [0, -30, 560, 320],
};

const localReview = {
  id: 'local-review', panel: 'review', label: 'Review before the PR', category: 'Layered verification', tone: 'amber',
  title: 'Catch the obvious issues before the PR.',
  description: 'Run a local review as part of implementation. Let the agent fix the findings before it asks another person to load the whole change into their head.',
  points: ['Use a separate review pass with the relevant domain skills.', 'Inspect the actual diff, run checks, and exercise the feature.', 'Keep independent CI review and human judgment after the PR opens.'],
  exampleLabel: 'THE REVIEW CONTRACT',
  example: 'A review returns concrete findings and evidence. After the agent fixes them, it reruns the affected checks and brings the results into the PR.',
  takeaway: 'Make the PR the first clear handoff, not the first quality check.',
  diagramStage: 5, view: [0, 0, 980, 565],
};

const productionAgents = {
  id: 'production-agents', panel: 'production', label: 'Watch after deployment', category: 'Production feedback', tone: 'teal',
  title: 'Keep watching after the release.',
  description: 'Production agents keep watching after a PR is merged and deployed. When a new issue is linked to the change, automatically alert its author immediately with the evidence needed to investigate their work.',
  points: ['Connect deployments to their PRs, authors, and service owners.', 'Look for new errors and regressions against a recent baseline.', 'Route actionable signals promptly; include evidence and uncertainty.'],
  exampleLabel: 'AN ACTIONABLE FOLLOW-UP',
  example: '“A new timeout pattern appeared after your rollout. Here are the affected route, first-seen time, example traces, and deployment link. Can you investigate?”',
  takeaway: 'Get the signal, evidence, and next action to the right person quickly.',
  diagramStage: 9, view: [0, 0, 980, 748],
};

const learningLoop = {
  id: 'learning-system', panel: 'learning', label: 'Improve the earliest step', category: 'Prevention compounds', tone: 'teal',
  title: 'Make the next attempt better.',
  description: 'Fixing the current change is only the first pass. Distill the general lesson, put it where the next agent will use it, and verify that it prevents the same mistake.',
  points: ['Collect patterns across PR comments, checks, logs, and incidents.', 'Change the earliest relevant skill, plus downstream review and tests.', 'Give the update an owner; check whether recurrence actually falls.'],
  exampleLabel: 'FROM COMMENT TO CAPABILITY',
  example: '“This needs pagination” becomes a tech-spec question, a backend implementation rule, a review criterion, and a behavior test with a realistic data volume.',
  takeaway: 'The goal is better first attempts, as well as better detection.',
  diagramStage: 10, view: [0, 0, 980, 748],
};

const projectManager = {
  id: 'project-manager', panel: 'manager', label: 'A shared project-manager agent', category: 'Reduce cognitive load', tone: 'teal',
  title: 'Let an agent keep track of the work.',
  description: 'A shared project-manager agent gives everyone a current view of tickets, open PRs, reviews, blockers, and next actions—without reconstructing it all by hand.',
  points: ['Connect tickets, PRs, CI, reviewers, and deployment evidence.', 'Distinguish in progress, review-ready, blocked, merged, and deployed.', 'Answer “What needs my attention?” with owners and source links.'],
  exampleLabel: 'ONE QUESTION, A USEFUL ANSWER',
  example: '“What should I focus on today?” The agent surfaces your review requests, blocked work, changes ready for review, and tickets awaiting release confirmation.',
  takeaway: 'People set priorities. The agent keeps the shared picture current.',
  diagramStage: 11, view: [0, 0, 980, 748],
};

const modelRunway = {
  id: 'model-runway', panel: 'runway', label: 'Be ready for better models', category: 'Why build this now', tone: 'teal',
  title: 'Build now. Be ready for the next leap.',
  description: 'More chips and more capable hardware can expand the compute available to train and run models. Our opportunity is to turn that progress into larger delegated tasks and more useful work in parallel.',
  points: ['Build the context, domain skills, review, and feedback system now.', 'Evaluate each new model against our own tasks and failure cases.', 'Expand scope and concurrency as the evidence earns more trust.'],
  exampleLabel: 'WHAT WE GET TO KEEP',
  example: 'When a stronger model arrives, it inherits our specs, tools, domain knowledge, checks, and lessons. We can put the improvement to work instead of rebuilding the workflow.',
  takeaway: 'Stronger models should multiply a system that is already ready.',
  diagramStage: 11, view: [0, 0, 980, 748],
};

const base = pipelineSteps.map((step, diagramStage) => ({ ...step, diagramStage }));
export const steps = [
  ...base.slice(0, 2), domainSkills,
  ...base.slice(2, 6), localReview,
  ...base.slice(6, 10), productionAgents,
  base[10], learningLoop, base[11], projectManager, modelRunway,
];
